### ISSUE TITLE
Problem with separator and delimiter

### ISSUE THREAD

**Issue by ghost** [emcien/number-helpers-coffeescript#10]
When I try to change the separator to "," with number_to_currency, it also changes the delimiter to the same symbol, independently if I set the delimiter to "." or not.

**Comment by rapcal** [comment]
The problem appears to be [this line](https://github.com/emcien/number-helpers-coffeescript/blob/1d224a0eab05c658b4708e451a29da975a998905/lib/number_helpers.js#L32).

Change it to something like...

``` javascript
baseResult = delimited.split('.');
result = baseResult.slice(0, -1).join(_delimiter) + _separator + baseResult.slice(-1);
```

... and it should work

**Comment by ghost** [comment]
Great - it works ;-)
